### ISSUE TITLE
Can't create an account.

### ISSUE THREAD

**Issue by damani42** [python/bugs.python.org#46] opened 2020-01-30 15:20 UTC
I have tried to create an account multiple times today, but I didn't received the mail confirmation. I have checked my spam folder. The username is damani.

**Comment by Mariatta** [comment] 2020-01-30 17:38
I did not see the user damani in b.p.o, so it wasn't created.

Was there error message?

**Comment by damani42** [comment] 2020-01-30 22:44
No error, I'm redirect to this page:

https://bugs.python.org/user?@template=rego_progress

But I have no mail. I have just tried again right now.

**Comment by damani42** [comment] 2020-02-03 09:04
I have still the problem.

**Comment by vstinner** [comment] 2020-02-05 10:21
@damani42 told me on IRC that he only filled 3 fields in the registration form:

* login name 
* login password 
* email address 

I asked because once there was an issue on email confirmation for users who filled the homepage (URL) field.

**Comment by vstinner** [comment] 2020-02-05 13:48
On bugs.python.org side, multiple emails are logged as sent. It may be an issue on @damani42 side: maybe his email server dropped these emails, maybe seen as spam.

**Comment by rouilj** [comment] 2020-07-11 20:58
> @damani42 told me on IRC that he only filled 3 fields in the registration form:
> 
> * login name
> * login password
> * email address
> 
> I asked because once there was an issue on email confirmation for users who filled the homepage (URL) field.

@vstinner was the issue with the homepage field fixed? It looks like: https://github.com/python/bugs.python.org/issues/52 may be caused by homepage url validation. I looked at the tracker and on first glance at least the detector looks
valid.

-- rouilj

**Comment by nmaynes** [comment] 2020-07-31 11:35
I ran into a similar problem today when trying to register. Received the homepage url validation error. I provided a value like, blog.mysite.com instead of https://blog.mysite.com. The verification link failed until I went back to the registration page and updated the homepage value. I am happy to help if someone can point me to where the code is to make changes. I would lean towards front end validation or remove the homepage URL from the registration page.

**Comment by rouilj** [comment] 2020-07-31 14:09
The registration page makes no changes to the database, so it's not subject to the backend validation.
Once the registration is accepted the database changes happen and the validation runs.

There are four ways to make this better in degree of difficulty.

1) Remove the homepage from the registration page html/user.register.html. Near line 49 in:
    https://hg.python.org/tracker/python-dev/file/0d0e7ce385e7/html/user.register.html#l49

    IIRC the user is presented with their configuration page when they complete registration
    so they can enter the url at that point. If they enter a bad url, they will find out when they
    submit the change.

2) Add directions saying the URL must start with https or http by replacing the td, /td tags with a span /span
    and wrap the span in a td /td. Then add the directions after the span.

3) Modify the detector at https://hg.python.org/tracker/python-dev/file/0d0e7ce385e7/detectors/userauditor.py#l44
    and change the code that validates the url to:
    1) check if it's valid
    2) if it's invalid, change the value to 'INVALID: ' followed by original homepage text.
        There is no way to tell the user that this happened, (roundup probably needs a soft-error exception) without
        aborting the registration. Again IIRC the user is left looking at their page, so they may notice the issue and fix
        it.  Not great. If I had implemented the soft error method it could be made much better.

4) do client side validation at the time of registration. This can be a javascript validation library and can be
    very involved. Alternatively use HTML5 validation supported by the browsers by adding the type=url
    and pattern="^https?://" attributes to the generated input tag. Note this will also require that directions
    be added (see item 2) so the user has an idea what is a valid url. To do this, change the existing:
            tal:content="structure context/homepage/field"
        to
            tal:content="structure python:context.organisation.field(type='url', pattern='^https?://')"

   and it will generate an input box with the needed attributes.

Note I am not sure if the maintainers will have the time/will to make the changes but...

-- rouilj

**Comment by nmaynes** [comment] 2020-07-31 14:42
I think the first option makes the most sense. A home page is not required to create an account and can cause problems if the value is filled in with errors that are difficult to understand for new users. Unless this is being used as a kind of new user filter, it is better, at least in my humble opinion, to ask for the required fields at sign up and allow the user to update once registered. 

So is the code for bugs.python.org impossible/difficult to create a PR for? I would be happy to make the actual changes as it seems to be a simple issue that can help teach me the pull request process for this project.

EDIT: It looks like the patch creation process is a little different for b.p.o. I'll do a little research and see if I can get the Docker container up and running to create a patch.

**Comment by rouilj** [comment] 2020-07-31 18:47
@Mariatta @ezio-melotti  is there a git clone of the roundup bpo tracker that nmaynes can do a pull request against?

Alternatively I can talk a maintainer (maybe ezio has a few cycles?) through the change that is needed if it is acceptable.

-- rouilj

**Comment by Mariatta** [comment] 2020-07-31 19:41
I think this is the repo now? https://github.com/psf/bpo-roundup 
It seems like all info in https://wiki.python.org/moin/TrackerDevelopment about mercurial are all outdated.

**Comment by nmaynes** [comment] 2020-07-31 20:02
I ran into the outdated instructions today. Tried to read through the text files in the new repo and change the docker image so it could run the appropriate scripts but kept running into issues. 

I have a few cycles over the next two weeks that I would be happy to contribute to updating the docs/Docker image. I probably need a bit of guidance on how the git repo is structured compared to the TrackerDevelopment wiki page.

**Comment by Mariatta** [comment] 2020-07-31 20:08
It seems the correct repo is at https://github.com/psf/bpo-tracker-cpython according to https://github.com/python/bugs.python.org/issues/2#issuecomment-667323839

**Comment by berkerpeksag** [comment] 2020-07-31 20:20
BTW, I've already set up my development environment and I can quickly remove the homepage field from `user.register.html`.

**Comment by rouilj** [comment] 2020-07-31 23:35
Looks like you gal/guys have it in hand. FYI I am going to unwatch this issue so @rouilj me if you need assistance.
I may try cloning the bpo tracker instance and give it a whirl with roundup 2.0.0 running under python 2. I am interested
in getting the openid stuff into roundup core or wiki.

**Comment by berkerpeksag** [comment] 2020-07-31 23:57
Fixed in https://github.com/psf/bpo-tracker-cpython/commit/515d0ad00bf2cb9574e721c32e8b14d532e3bd36. I've also managed to reproduce the problem locally by filing the homepage field with an invalid input and verified that the proposed fix by John works as expected. IIRC, the fix should be online in an hour or so. Thank you all!

**Closed as completed by berkerpeksag** 2020-07-31 23:57 UTC
